owner: remix-bot
repo: status

sites:
  - name: Remix Dashboard
    url: https://remix.fairuse.org

status-website:
  baseUrl: /status
  logoUrl: https://remix.fairuse.org/assets/icon.png
  name: Remix Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://remix.fairuse.org
